---
- name: Include vars for RedOS
  include_vars:
    file: vars/red.yml

- name: Generate prompt
  become: true
  blockinfile:
    path: "{{ item }}"
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
    block: |
      if [[ $UID == 0 ]]
         then
           PS1="[\[\033[1;32m\]{{ version }}\[\033[00m\]|\[\033[1;31m\]\u@\[\033[1;33m\]\h:\[\033[1;31m\]\w]# \[\033[00m\]"
         else
           PS1="[\[\033[1;32m\]{{ version }}\[\033[00m\]|\[\033[1;32m\]\u@\[\033[1;33m\]\h:\[\033[1;32m\]\w]$ \[\033[00m\]"
      fi
  loop:
    - /etc/bashrc
    - /root/.bashrc
    - /home/vagrant/.bashrc

- name: Create motd directory
  become: true
  file:
    path: "/etc/update-motd.d"
    state: directory

- name: Copy motd files
  become: true
  copy:
    src: "files/{{ item }}"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: 0755
  loop:
    - 00-header
    - 10-sysinfo
    - 90-footer

- name: Clean unessesary packages
  become: true
  package:
    name:
      - libmtp-runtime
      - qt4-doc-html
      - wxmaxima
      - inkscape
      - synaptic
      - jag
      - fly-all-optional
      - blender
      - swfdec-mozilla
      - maxima
      - qmmp
    state: absent
  when: '"Desktop" in type'

- name: Autoclean
  become: true
  yum:
    autoremove: yes

- name: Create directory
  file:
    path: /home/vagrant/.ssh
    state: directory
    mode: 0700

- name:
  uri:
    url: https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    validate_certs: no
    mode: '0600'

#- name: Copy using inline content
#  copy:
#    content: "{{ vagrant_key }}"
#    dest: /home/vagrant/.ssh/authorized_keys
#    mode: '600'

- name: Sync file system
  command: "sync"
