#! /bin/sh
set -euo pipefail

create_ps() {
  echo "Create PS for \${1}"
cat << EOF >> \${1}
if [[ \$UID == 0 ]]
then
  PS1="[\[\033[1;32m\]${TARGET}\[\033[00m\]|\[\033[1;31m\]\u@\[\033[1;33m\]\h:\[\033[1;31m\]\w]# \[\033[00m\]"
else
  PS1="[\[\033[1;32m\]${TARGET}\[\033[00m\]|\[\033[1;32m\]\u@\[\033[1;33m\]\h:\[\033[1;32m\]\w]$ \[\033[00m\]"
fi
EOF
}

echo "Configuring Vagrant user"
mkdir -p /home/vagrant/.ssh
curl "https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub" -o "/home/vagrant/.ssh/authorized_keys"
chown -R vagrant:vagrant /home/vagrant

create_ps /etc/bashrc

echo "Vagrant user configured"

