---
# generate some files for vagrant
- name: Generate some files for vagrant & provisioning
  hosts: default
  #vars_files:
  #  - vars/vars.yml
  #pre_tasks:
  #  - name: Install python for Ansible
  #    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  #    changed_when: False
  tasks:
#    - name: Include vars for AltLinux
#      include_vars:
#        - vars/alt.yml
#      when: ansible_facts['distribution']|lower == "altlinux"

    - name: Import tasks for AltLinux
      import_tasks: OS/alt.yml
      when: ansible_facts['distribution']|lower == "altlinux"

#    - name: Include vars for RedOS
#      include_vars:
#        - vars/red.yml
#      when: ansible_facts['distribution']|lower == "red"

    - name: Import tasks for RedOS
      import_tasks: OS/red.yml
      when: ansible_facts['distribution']|lower == "red"

    - name: Import tasks for AstraLinux
      import_tasks: OS/astra.yml
      when: ansible_facts['distribution'] == "Astra Linux (Orel)"

    - name: Generate info
      delegate_to: localhost
      template:
        src: "templates/info.json.j2"
        dest: "../data/info.json"

    - name: Generate metadata
      delegate_to: localhost
      template:
        src: "templates/metadata.json.j2"
        dest: "../data/metadata.json"

    - name: Generate Vgarantfile
      delegate_to: localhost
      template:
        src: "templates/Vagrantfile.j2"
        dest: "../data/Vagrantfile"
