---
# Remove most packages from tasksel Fly Desktop
- name: 'Provision Image'
  hosts: default
  become: true
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
  tasks:
    - name: Remove Packages
      package:
        name: '{{ item }}'
        state: absent
      loop:
        - libmtp-runtime
        - qt4-doc-html
        - wxmaxima
        - inkscape
        - synaptic
        - jag
        - fly-all-optional
        - blender
        - swfdec-mozilla
        - maxima
        - qmmp
        - linux-image-4.15.3-2-hardened

    - name: Autoclean
      apt:
        autoremove: true

    - name: Install Kernel
      package:
        name: '{{ item }}'
        state: present
      loop:
        - linux-image-5.2*

    - name: Change console PS for Debian family OS
      blockinfile:
        path: '{{ item }}'
        block: |
          REGION='{{ ansible_date_time.date }}'
          if [[ $(id -u) -eq 0 ]];
            then
              PS1="[\[\033[1;32m\]$REGION\[\033[00m\]|\[\033[1;31m\]\u@\[\033[1;33m\]\h:\[\033[1;31m\]\w]# \[\033[00m\]"
            else
              PS1="[\[\033[1;32m\]$REGION\[\033[00m\]|\[\033[1;32m\]\u@\[\033[1;33m\]\h:\[\033[1;32m\]\w]$ \[\033[00m\]"
          fi
      loop:
        - /etc/bash.bashrc
